// TODO: Include packages needed for this application
// Require Inquirer and fs package to prompt the user information
const inquirer = require('inquirer');
const fs = require('fs');

// Create an array of questions for user input
const questions = [
    {
      type: 'input',
      name: 'username',
      message: 'What is your GitHub Username?'
    },
    {
      type: 'input',
      name: 'title',
      message: 'What is the title of your Github repo?'
    },
    {
        type: 'input',
        name: 'description',
        message: 'Can you provide a description of your project?'
    },
    {
        type: 'input',
        name: 'installation',
        message: 'What are the necessary steps to install your project?'
    },
    {
        type: 'input',
        name: 'usage',
        message: 'What are the guidelines for using your project?'
    },
    {
        // notice type is list instead of input so that can select choice from array "choices"
        type: 'list',
        name: 'license',
        message: 'Choose a license for your project:',
        choices: ['GNU AGPLv3', 'GNU GPLv3', 'GNU LGPLv3', 'Mozilla Public License 2.0', 'Apache License 2.0', 'MIT License', 'Boost Software License 1.0', 'The Unlicense'] 
    },
    {
        type: 'input',
        name: 'contributing',
        message: 'Provide guidelines for other developers who want to contribute to your project:'
    },
    {
        type: 'input',
        name: 'tests',
        message: 'Provide examples on how to run tests for your project:'
    },
    {
        type: 'input',
        name: 'questions',
        message: 'Are there any frequently asked questions that need to be addressed?'
    }
  ];
  

// Create a function to write README file
const writeToFile = ('README.md', data) => {
    // fileName = 'README.md';
    // data = readmeContent= content written to file
    // function (err) = callback function after file has been written
    // fs.writeFile = part of built-in Node.js file system (fs) which provides API for interacting with the file system (allows user to write data to a file)
    fs.writeFile('README.md', data, (err) => 
        // Did an error occur while writing the file?
            // if(err) {
            //    console.log(err);
            // } else {
            //    console.log('Your README.md file has been successfully created!')
        err ? console.log(err) : console.log('Your README.md file has been successfully created!')
);
}

// Create a function to initialize app
// prompts the user for information using the inquirer package, generates README content, and writes to file (with call to writeToFile)
const init = () => {
    inquirer.prompt(questions).then((data) => {
    const readmeContent = ({data.title, data.description, data.installation, data.usage, data.contributing, data.tests, data.questions, data.username }) =>
    
    `# ${data.title}

    ${data.description}
    
    ## Table of Contents
    
    - [Installation](#installation)
    - [Usage](#usage)
    - [License](#license)
    - [Contributing](#contributing)
    - [Tests](#tests)
    - [Questions](#questions)
    
    ## Installation
    
    ${data.installation}
    
    ## Usage
    
    ${data.usage}
    
    ## License
    
    This project is licensed under the ${data.license} license.
    
    ## Contributing
    
    ${data.contributing}
    
    ## Tests
    
    ${data.tests}
    
    ## Questions
    
    ${data.questions}
    
    ---
    
    This README was generated by ${data.username}`;
    
        writeToFile('README.md', readmeContent);

    });
};

// Function call to initialize app
init();
